version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

    steps:
      - checkout

      - run:
        name: Setup VirtualEnv
        command: |
          echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test-ci

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and push Docker image
          command: |
            docker build -t joschi64/homagix:$TAG
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push joschi64/homagix:$TAG
