export const ERROR_OCCURED = 'ERROR_OCCURED'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const STARTDATE_CHANGED = 'STARTDATE_CHANGED'
export const WEEKPLAN_LOADED = 'WEEKPLAN_LOADED'

export const GET_INGREDIENTS = 'GET_INGREDIENTS'
export const INGREDIENTS_LOADED = 'INGREDIENTS_LOADED'
export const INGREDIENT_CHANGED = 'INGREDIENT_CHANGED'

export const GET_UNITS = 'GET_UNITS'
export const UNITS_LOADED = 'UNITS_LOADED'

export const DISH_DECLINED = 'DISH_DECLINED'
export const TOGGLE_ACCEPTANCE = 'TOGGLE_ACCEPTANCE'
export const ACCEPTANCE_CHANGED = 'ACCEPTANCE_CHANGED'

export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const RESTORE_ITEM = 'RESTORE_ITEM'
export const CHANGES_CHANGED = 'CHANGES_CHANGED'
export const SET_ACTIVE_ITEM = 'SET_ACTIVE_ITEM'
export const UPDATE_AMOUNT = 'UPDATE_AMOUNT'

export const SHOPPING_DONE = 'SHOPPING_DONE'

export const RESET_STORE = 'RESET_STORE'
