export const ERROR_OCCURED = 'ERROR_OCCURED'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const STARTDATE_CHANGED = 'STARTDATE_CHANGED'
export const GET_PROPOSALS = 'GET_PROPOSALS'
export const PROPOSALS_LOADED = 'PROPOSALS_LOADED'

export const GET_INGREDIENTS = 'GET_INGREDIENTS'
export const INGREDIENTS_LOADED = 'INGREDIENTS_LOADED'

export const GET_UNITS = 'GET_UNITS'
export const UNITS_LOADED = 'UNITS_LOADED'

export const DISH_DECLINED = 'DISH_DECLINED'
export const TOGGLE_ACCEPTANCE = 'TOGGLE_ACCEPTANCE'
export const ACCEPTANCE_CHANGED = 'ACCEPTANCE_CHANGED'

export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const RESTORE_ITEM = 'RESTORE_ITEM'
export const CHANGES_CHANGED = 'CHANGES_CHANGED'

export const SHOPPING_DONE = 'SHOPPING_DONE'
