export const ERROR_OCCURED = 'ERROR_OCCURED'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const GET_PROPOSALS = 'GET_PROPOSALS'
export const PROPOSALS_LOADED = 'PROPOSALS_LOADED'

export const GET_INGREDIENTS = 'GET_INGREDIENTS'
export const INGREDIENTS_LOADED = 'INGREDIENTS_LOADED'

export const DISH_DECLINED = 'DISH_DECLINED'
export const DISH_ACCEPTED = 'DISH_ACCEPTED'
